import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';

const repo = 'TraderAlice/OpenAlice';
const cdn = 'https://download.openalice.ai/manifest.json';
const formulaPath = new URL('../Formula/openalice.rb', import.meta.url);
export const hash = bytes => createHash('sha256').update(bytes).digest('hex');
export const formulaVersion = text => text.match(/^  version "(\d+\.\d+\.\d+)"$/m)?.[1];

export function validateRelease(release, stable, current = '') {
  assert.equal(release.draft, false);
  assert.equal(release.prerelease, false);
  assert.match(release.tag_name, /^v\d+\.\d+\.\d+$/);
  const version = release.tag_name.slice(1);
  assert.equal(stable.channel, 'stable');
  assert.equal(stable.version, version, 'GitHub release is not yet active on the stable CDN');
  if (current) {
    const old = formulaVersion(current);
    assert.ok(old, 'Existing formula has no stable version');
    const a = version.split('.').map(BigInt), b = old.split('.').map(BigInt);
    const difference = a.map((v, i) => v - b[i]).find(v => v !== 0n) ?? 0n;
    assert.ok(difference >= 0n, 'Refusing to downgrade the tap');
  }
  return version;
}

export function validateFormula(formula, manifest, version) {
  const base = `https://github.com/${repo}/releases/download/v${version}`;
  assert.equal(formulaVersion(formula), version);
  assert.equal(manifest.schemaVersion, 1);
  assert.equal(manifest.version, version);
  assert.equal(manifest.assetBaseUrl, base);
  const expected = ['darwin-arm64', 'darwin-x64', 'linux-arm64', 'linux-x64'];
  const targets = expected.map(key => {
    const [platform, arch] = key.split('-');
    const found = manifest.targets.filter(t => t.platform === platform && t.arch === arch);
    assert.equal(found.length, 1, `Missing/duplicate ${key}`);
    assert.match(found[0].sha256, /^[a-f0-9]{64}$/);
    const name = `openalice-cli-${version}-${key}.tar.gz`;
    const url = `${base}/${name}`;
    assert.ok(formula.includes(`url "${url}"\n      sha256 "${found[0].sha256}"`), `Formula mismatch: ${key}`);
    return { name, url, sha256: found[0].sha256 };
  });
  assert.equal((formula.match(/^\s+url "/gm) ?? []).length, 4);
  return targets;
}

async function request(url) {
  const headers = { 'User-Agent': 'OpenAlice-homebrew-sync' };
  // The scoped Actions token is sent only to GitHub's API, never release assets/CDN.
  if (url.startsWith('https://api.github.com/') && process.env.GH_TOKEN)
    headers.Authorization = `Bearer ${process.env.GH_TOKEN}`;
  const response = await fetch(url, { headers, signal: AbortSignal.timeout(120_000) });
  assert.ok(response.ok, `${url}: HTTP ${response.status}`);
  return response;
}

export async function sync(write = false) {
  const release = await (await request(`https://api.github.com/repos/${repo}/releases/latest`)).json();
  const stable = await (await request(cdn)).json();
  const current = await readFile(formulaPath, 'utf8').catch(e => { if (e.code === 'ENOENT') return ''; throw e; });
  const version = validateRelease(release, stable, current);
  const base = `https://github.com/${repo}/releases/download/v${version}`;
  const formula = await (await request(`${base}/openalice.rb`)).text();
  const asset = release.assets.find(a => a.name === 'openalice.rb');
  assert.equal(asset?.digest, `sha256:${hash(formula)}`, 'Formula differs from GitHub asset digest');
  if (formulaVersion(current) === version) {
    assert.equal(current, formula, 'Refusing to replace bytes of an already-published version');
    console.log(`OpenAlice ${version}: already current; no archive downloads or writes.`);
    return;
  }
  const manifest = await (await request(`${base}/cli-package-channels.json`)).json();
  const targets = validateFormula(formula, manifest, version);
  await Promise.all(targets.map(async target => {
    const sidecar = (await (await request(`${target.url}.sha256`)).text()).trim().split(/\s+/);
    assert.equal(sidecar[0], target.sha256);
    assert.equal(sidecar[1]?.replace(/^\*/, ''), target.name);
    const digest = createHash('sha256');
    for await (const chunk of (await request(target.url)).body) digest.update(chunk);
    assert.equal(digest.digest('hex'), target.sha256, `Archive mismatch: ${target.name}`);
    console.log(`Verified ${target.name}`);
  }));
  // Recheck current channel authority before publishing the generated bytes.
  const fresh = await (await request(`https://api.github.com/repos/${repo}/releases/latest`)).json();
  assert.equal(fresh.id, release.id, 'A newer release appeared; retry against that release');
  validateRelease(fresh, await (await request(cdn)).json(), current);
  if (write) {
    await mkdir(new URL('../Formula/', import.meta.url), { recursive: true });
    await writeFile(formulaPath, formula);
  }
  console.log(`OpenAlice ${version}: verified four public archives; ${write ? 'formula updated' : 'read-only check'}.`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  assert.ok(process.argv.slice(2).every(arg => arg === '--write'), 'Usage: node scripts/sync.mjs [--write]');
  await sync(process.argv.includes('--write'));
}
